# =============================================================================
# INCLUDE
# =============================================================================

include:
  - project: "shared/devops/pipeline"
    file: "/base.yml"

# =============================================================================
# GLOBAL VARIABLES
# =============================================================================
