# =============================================================================
# BASE CONFIGURATION
# =============================================================================

version: "3.7"

# =============================================================================
# SERVICES
# =============================================================================

services:

# =============================================================================
# ECS DEPLOY
# =============================================================================

  ecs-deploy:
    container_name: ${CONTAINER_NAME}
    env_file: ./.env
    build:
      context: ./${PATH_DOCKERFILE}
      dockerfile: Dockerfile
    entrypoint: >
      /bin/sh -c "
        set -e
        ./deploy.sh
        /bin/bash || exit 0
      "
    restart: unless-stopped
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "20"
    networks:
      - ecs-deploy

# =============================================================================
# NETWORKS
# =============================================================================

networks:
  ecs-deploy:
